import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../lib/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nonggor",
  description: "Generated by Istiak Hasan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
        <link rel="icon" href="/nongor.png" type="image/png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ✅ Providers must be inside <body>, not wrapping <html> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
